### ISSUE TITLE
Lag when using invisible widget

### ISSUE THREAD

**Issue by cryptanym** [RVxLab/hcaptcha#9]
I copied the example invisible widget into my application, when clicking the button it takes about 5 seconds before the captcha shows up, and it skips over my form validation.

Edit: Seems hCaptcha is just slow... Would there be a way to add a class to the button, just as disabled, when the hCaptcha is loading, or to show a loading bar.

My form still does not get validated when clicking the button, I'm using [MaterializeCSS](https://materializecss.github.io/materialize/getting-started.html)

**Comment by RVxLab** [comment]
There is no built-in method to do what you want to do. You could do this yourself with a little JavaScript. 

As for the performance, if this is coming from hCaptcha’s end then there isn’t a whole lot to do from the package end. 

Does this happen locally only? If so, can the network tab give some more insight?

**Comment by cryptanym** [comment]
I checked the network tab, there seems to be no more insight apart from hcaptcha is just slow in general, it wouldn't be as bad if it was more user friendly, say button was disabled and a preloader popped up beside it maybe, I see there is two callbacks in this package, maybe one could be added and when the button is pressed but before the captcha is shown, so I can display some loading html, and then hide it once it's loaded, I tried onclick="" but that didn't work, so I might look into using an event listener, otherwise I would just use the normal box because it's more demonstrative to the user something is actually happening while they wait for hcaptcha to load and not to spam press the button or refresh the page, it would also be handy to be able to preload hcaptcha while the user is filling out the form, because once it's loaded the first time, clicking off the captcha and and on to the button again is quite fast.

**Comment by RVxLab** [comment]
I added the ability to publish the views, so if you want to have a different default that can do what you need it to do you can take a look at it.

If you want to give it a try, you can reference commit `f443b0f977b698a179178a30571bdaf63d3fe357` in your composer.json. Composer doesn't recommend this, so use it at your own risk.

```json
"require": {
    "rvxlab/hcaptcha": "dev-main#f443b0f977b698a179178a30571bdaf63d3fe357",
}
```

And run `composer update rvxlab/hcaptcha`.

The new features currently in the issue tracker will land with v5.1.

I'm closing this issue for now as there is not much more I can do to help as this is a specific issue to your project.
